# Generated by Django 3.2.5 on 2021-07-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data time on which the object was created. ', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200)),
                ('person_type', models.CharField(max_length=20)),
                ('personal_idendification_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'owners',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
