# Generated by Django 3.2.5 on 2021-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data time on which the object was created. ', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('cedula_catastral', models.CharField(max_length=40)),
                ('address_or_name_properties', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=6)),
                ('real_estate_registration_number', models.CharField(max_length=16)),
                ('owners', models.ManyToManyField(db_table='properties_owners', to='owners.Owner')),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
